name: ServerStats
main: me.rosswalker.serverstats.ServerStats
version: 1.0.5
authors: [uberKat, DicaxDorcas]
commands:
  ss:
    description: Central ServerStat Command
    aliases: [serverstats, sstats]

permissions:
    ServerStats.*:
        description: Gives access to all ServerStats commands.
        children:
            ServerServerStats.check: true
            ServerStats.player: true
            ServerStats.player.other: true
    ServerStats.check:
        description: Allows a player to check the statistics of the server.
        default: op
    ServerStats.player:
        description: Allows a player to view their own statistics.
        default: op
    ServerStats.player.other:
        description: Allows a player to view other's statistics.
        default: op
