name: ServerStats
main: org.orecraft.serverstats.ServerStats
version: 1.0.5vol
authors: [uberKat, DicaxDorcas]
commands:
  ss:
    description: Central ServerStat Command
    aliases: [serverstats, server]

permissions:
    stats.*:
        description: Gives access to all ServerStats commands.
        children:
            stats.info: true
            stats.credits: true
            stats.help: true
            stats.stats: true
            stats.player: true
            stats.player.lookup: true
            stats.reset: true
            stats.null: true
            stats.unknown: true
    stats.info:
        description: Allows you to use the ServerStats "info" command.
        default: op
    stats.credits:
        description: Allows you to use the ServerStats "credits" command.
        default: op
    stats.help:
        description: Allows you to use the ServerStats "help" command.
        default: op
    stats.stats:
        description: Allows you to use the ServerStats "stats" command.
        default: op
    stats.player:
        description: Allows you to use the ServerStats "player" command.
        default: op
    stats.player.lookup:
        description: Allows you to use the ServerStats "player" command to find players.
        default: op
    stats.reset:
        description: Resets ServerStats data.
        default: op
    stats.null:
        description: Allows you to use the "ServerStats" command.
        default: op
    stats.unknown:
        description: Allows you to receive the ServerStats "unknown" message.
        default: op
