name: ServerStats
main: me.rosswalker.serverstats.ServerStats
version: 1.0.5
authors: [uberKat, DicaxDorcas]
commands:
  ss:
    description: Central ServerStat Command
    aliases: [serverstats, server]

permissions:
    stats.*:
        description: Gives access to all ServerStats commands.
        children:
            stats.stats: true
            stats.player: true
            stats.player.lookup: true
            stats.reset: true
    stats.stats:
        description: Allows you to use the ServerStats stats command.
        default: op
    stats.player:
        description: Allows you to use the ServerStats player command.
        default: op
    stats.player.lookup:
        description: Allows you to use the ServerStats player command to find players.
        default: op
    stats.reset:
        description: Resets ServerStats data.
        default: op
